data:

  distribution:
    seed: 42
    type: static
    num_requests: 100000
    num_keys: 50
    key_range:
      first_key: 1
      last_key: 50
    freq_windows: [ 10, 100, 1000 ]

  access_pattern:
    zipf:
      alpha: 0.8
      alpha_start: 0.8
      alpha_end: 1.2
      time_steps: 10
    locality:
      prob: 0.7

  temporal_pattern:
    burstiness:
      burst_high: 1.0
      burst_low: 10.0
      burst_every: 100
      burst_peak: 20
    periodic:
      base_scale: 5
      amplitude: 5

  sequence:
    len: 25
    embedding_dim: 32

  dataset:
    training_perc: 0.7
    static_save_path: data/static_access_logs.csv
    dynamic_save_path: data/dynamic_access_logs.csv


model:

  general:
    num_features: 5
    save_path: model/trained_lstm_model.pt

  params:
      hidden_size: 256
      num_layers: 3
      bias: false
      batch_first: true
      dropout: 0.2
      bidirectional: false
      proj_size: 0


training:

  general:
    num_epochs: 10
    batch_size: 64

  optimizer:
    type: adamw
    learning_rate: 0.001
    weight_decay: 0.05
    momentum: 0.9


validation:

  cross_validation:
    num_folds: 10
    num_epochs: 5

  early_stopping:
    patience: 5
    delta: 0.0005

  search_space:
    model:
      params:
        hidden_size_range:
        - 64
        - 128
        - 256
        num_layers_range:
        - 2
        - 3
        - 4
        dropout_range:
        - 0.1
        - 0.3
        - 0.5
    training:
      learning_rate_range:
      - 0.0005
      - 0.001
      - 0.003
      - 0.005


evaluation:
  top_k: 3


testing:
  general:
    batch_size: 64
