data:
  distribution_type: static
  num_requests: 5000
  num_keys: 50
  alpha: 1.3
  alpha_start: 1.3
  alpha_end: 1.8
  time_steps: 100
  seq_len: 50
  freq_timestamp: 5
  training_perc: 0.7
  static_dataset_path: data/static_access_logs.csv
  dynamic_dataset_path: data/dynamic_access_logs.csv
model:
  params:
    hidden_size: 64
    num_layers: 3
    bias: false
    batch_first: true
    dropout: 0.5
    bidirectional: false
    proj_size: 0
  features_dim: 5
  model_save_path: model/trained_lstm_model.pt
training:
  epochs: 50
  batch_size: 256
  learning_rate: 0.003
  optimizer: rmsprop
  weight_decay: 0
  momentum: 0.9
validation:
  num_folds: 3
  epochs: 5
  search_space:
    model:
      params:
        hidden_size_range:
        - 64
        - 128
        - 256
        num_layers_range:
        - 2
        - 3
        - 5
        dropout_range:
        - 0.0
        - 0.1
        - 0.3
        - 0.5
    training:
      learning_rate_range:
      - 0.0005
      - 0.001
      - 0.003
evaluation:
  top_k: 3
  average: macro
early_stopping:
  patience: 5
  delta: 0.0001
testing:
  batch_size: 256
