data:
  distribution_type: static
  seed: 42
  num_requests: 50000
  num_keys: 500
  first_key: 1
  last_key: 501
  alpha: 1.3
  alpha_start: 1.3
  alpha_end: 1.8
  time_steps: 100
  seq_len: 50
  freq_timestamp: 5
  training_perc: 0.7
  static_dataset_path: data/static_access_logs.csv
  dynamic_dataset_path: data/dynamic_access_logs.csv
model:
  params:
    hidden_size: 128
    num_layers: 2
    bias: false
    batch_first: true
    dropout: 0.1
    bidirectional: false
    proj_size: 0
  features_dim: 1
  model_save_path: model/trained_lstm_model.pt
training:
  epochs: 50
  batch_size: 128
  learning_rate: 0.001
  optimizer: adamw
  weight_decay: 0.01
  momentum: 0.9
validation:
  num_folds: 3
  epochs: 3
  search_space:
    model:
      params:
        hidden_size_range:
        - 128
        - 256
        num_layers_range:
        - 2
        - 3
        dropout_range:
        - 0.1
        - 0.3
    training:
      learning_rate_range:
      - 0.001
      - 0.005
evaluation:
  top_k: 3
  average: macro
early_stopping:
  patience: 3
  delta: 0.001
testing:
  batch_size: 128
