model:
  input_size: 1
  hidden_size: 64
  num_layers: 2
  bias: True
  batch_first: True
  dropout: 0.0
  bidirectional: False
  proj_size: 0

training:
  epochs: 20
  batch_size: 64
  learning_rate: 0.001

data:
  n_requests: 10000
  n_keys: 5000
  alpha: 1.3
  alpha_start: 1.3
  alpha_end: 1.8
  time_steps: 100
  static_dataset_path: "../data/static_access_logs.csv"
  dynamic_dataset_path: "../data/dynamic_access_logs.csv"
