data:

  distribution_type: static

  num_requests: 10000
  num_keys: 10
  first_key: 1
  last_key: 10
  freq_windows: [10, 100, 1000]

  alpha: 0.5
  alpha_start: 0.5
  alpha_end: 1.0
  time_steps: 10

  burst_high: 1.0
  burst_low: 10.0
  burst_every: 100
  burst_peak: 20
  periodic_base_scale: 5
  periodic_amplitude: 5

  seed: 42
  seq_len: 25
  embedding_dim: 32
  freq_timestamp: 5

  training_perc: 0.7
  static_dataset_path: data/static_access_logs.csv
  dynamic_dataset_path: data/dynamic_access_logs.csv
model:
  params:
      hidden_size: 256
      num_layers: 3
      bias: false
      batch_first: true
      dropout: 0.2
      bidirectional: false
      proj_size: 0
  num_features: 5
  model_save_path: model/trained_lstm_model.pt
training:
  epochs: 10
  batch_size: 64
  learning_rate: 0.001
  optimizer: adamw
  weight_decay: 0.05
  momentum: 0.9
validation:
  num_folds: 3
  epochs: 3
  search_space:
    model:
      params:
        hidden_size_range:
        - 128
        - 256
        num_layers_range:
        - 2
        - 3
        dropout_range:
        - 0.1
        - 0.3
    training:
      learning_rate_range:
      - 0.001
      - 0.005
evaluation:
  top_k: 3
early_stopping:
  patience: 5
  delta: 0.0005
testing:
  batch_size: 64
