data:
  num_requests: 10000
  num_keys: 100
  alpha: 1.3
  alpha_start: 1.3
  alpha_end: 1.8
  time_steps: 100
  seq_len: 25
  freq_timestamp: 5
  training_perc: 0.7
  testing_perc: 0.2
  validation_perc: 0.1
  static_dataset_path: data/static_access_logs.csv
  dynamic_dataset_path: data/dynamic_access_logs.csv
model:
  hidden_size: 128
  num_layers: 5
  bias: true
  batch_first: true
  dropout: 0.0
  bidirectional: false
  proj_size: 0
  embedding_dim: 64
  model_save_path: model/trained_lstm_model.pt
training:
  epochs: 5
  batch_size: 128
  learning_rate: 0.005
validation:
  num_folds: 3
  embedding_dim_range:
  - 32
  - 64
  hidden_size_range:
  - 64
  - 128
  num_layers_range:
  - 1
  - 3
  - 5
  dropout_range:
  - 0.0
  - 0.1
  - 0.3
  learning_rate_range:
  - 0.001
  - 0.003
  - 0.005
