data:
  distribution_type: static
  num_requests: 1000
  num_keys: 20
  alpha: 1.3
  alpha_start: 1.3
  alpha_end: 1.8
  time_steps: 100
  seq_len: 50
  freq_timestamp: 5
  training_perc: 0.7
  static_dataset_path: data/static_access_logs.csv
  dynamic_dataset_path: data/dynamic_access_logs.csv
model:
  hidden_size: 256
  num_layers: 2
  bias: false
  batch_first: true
  dropout: 0.1
  bidirectional: false
  proj_size: 0
  model_save_path: model/trained_lstm_model.pt
training:
  epochs: 5
  batch_size: 128
  learning_rate: 0.0005
validation:
  num_folds: 3
  epochs: 3
  hidden_size_range:
  - 64
  - 128
  - 256
  num_layers_range:
  - 1
  - 2
  - 3
  dropout_range:
  - 0.0
  - 0.1
  - 0.3
  - 0.5
  learning_rate_range:
  - 0.0005
  - 0.001
  - 0.003